### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by nathanhaigh** [csiro-crop-informatics/biokanga#2] opened 2017-03-30 04:21 UTC
There should be a `CONTRIBUTING.md` file so people know how contributions should be made, the process involved etc. Is the intention to try and have a stable `master` and have development work take place on a `develop` branch or to have development take place on `master`?

GitHub has some guidelings for these here:
https://github.com/blog/1184-contributing-guidelines

**Comment by alexwhan** [comment] 2017-03-30 04:24
At the moment I've only referenced that in the Readme. It definitely needs
to be expanded on.
Yes, the branching model (from here on)  is that all development happens in
a branch *off* the `dev` branch. `master` should in future be restricted to
releases

**Comment by nathanhaigh** [comment] 2017-03-30 04:49
Something like this might be helpful:
https://github.com/hpcugent/easybuild-framework/blob/master/CONTRIBUTING.md

If I get a chance, I'll write one up and issue a pull request!

**Comment by kit4b** [comment] 2017-05-01 06:33
Any progress on this issue - it's been stalled for a month? Sounds like the current 'dev' branch is really intended as a 'test/acceptance' branch ( alexwhan: "_development happens in
a branch *off* the `dev` branch_" ) and should be renamed as such; with actual development occurring on a separate branch. End structure should be a branch 'dev', which is merged into a branch 'test' which is then merged into the 'master' with acceptance criteria established before the respective merges are accepted.
I would like to directly contribute but would firstly need the repository structure agreed and branch merge acceptance criteria established so as to minimise the regression risks.

**Comment by alexwhan** [comment] 2017-05-02 05:16
This is a fairly standard branching model, loosely following the guidelines here (http://nvie.com/posts/a-successful-git-branching-model/). The contributing page @nathanhaigh linked to is a great example I think. Including something like that should close this issue?

**Comment by nathanhaigh** [comment] 2017-05-02 05:35
The only downside to the branching model used by `EasyBuild` is that for a contributor, there are a bunch of extra steps required and you have to ensure pull requests are to the `dev` branch - it defaults to `master`.

**Comment by alexwhan** [comment] 2017-05-02 06:07
I think we can change the default pull request branch to dev

**Comment by kit4b** [comment] 2017-05-02 10:54
The 'A successful Git branching model' is essentially requiring developers to allow access to their private repositories when more than one developer is working on a given feature branch. Great if developers are on the same network, not so great if developers are distributed across multiple private networks with each isolated by firewalls and with NAT to contend with. Resolve this and I'm happy!

**Closed as completed** 2017-05-03 06:55 UTC
